### ISSUE TITLE
Have the option to enable cacheGetRequests by default

### ISSUE THREAD

**Issue by lostpebble** [trailsuite/react-inlinesvg#3]
So after figuring out the little configuration, this fork is exactly what I was looking for. So thanks for putting it together!

The only thing I would want more is the ability to change the default setting of `cacheGetRequest`. I agree that it should perhaps be off by default to let people decide... Or maybe not- SVGs are for the most part really tiny and caching should be desired, the only time I can see it not being desired is if you have a really large SVG (which is rare) and then perhaps in those situations the option would be available to set the prop `cacheGetRequest={false}` if it really affects performance somehow.

But in any case, just the ability to somehow globally set that prop's default value would be great.

**Comment by ifuller1** [comment]
I wanted to increase the chances of Mattew merging the change - but the truth is it's very unlikely now its es6.

Do you want to raise a PR that updates the docs and the default prop value? If so I'll merge it in.

Ian

**Comment by lostpebble** [comment]
Yes, I think it may be unlikely because the code has changed so much from coffee to es6. It also appears to be a bit stale at the moment, with the last commit 10 months ago and not much interaction in the issues, it doesn't seem matthewwithanm is very active with this package at the moment. Not sure what the best way forward is, I would prefer to be able to use this library through npm. But this is fine for now I guess.

**Comment by ifuller1** [comment]
This package is on npm. Afk right now but it's inline 'with cache'.
